- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - code
      - git
      - build-essential
      - curl
      - make
      - gnome-tweak-tool
      - python3-pip
      - emacs-nox