- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - code
      - git
      - build-essential
      - curl
      - make
      - gnome-tweaks
      - python3-pip
      - emacs-nox
      - openjdk-18-jdk
      - google-chrome-stable
      - discord
      - ca-certificates
      - docker-ce
      - docker-ce-cli
      - containerd.io 
      - docker-compose-plugin